apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ubuntu-set
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: testingnode
        ports:
        - containerPort: 22
