---
- name: Distribute ssh key
  hosts: all
  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_ed25519.pub') }}"

