---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-1
    image: testingnode:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: instance-2
    image: testingnode:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  # Add more instances as needed...
provisioner:
  name: ansible
verifier:
  name: ansible

